# Generated by Django 4.1.5 on 2023-01-10 19:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, help_text='Enter details', max_length=500, null=True)),
                ('Duration', models.TextField(choices=[('1 Month', '1 Month'), ('6 Months', '6 Months'), ('12 Months', '12 Months'), ('Other', 'Other')], default='')),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('profile_image', models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='profiles')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+972', max_length=128, region=None, unique=True)),
                ('current_plan', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='panel.plan')),
            ],
        ),
    ]
